# Generated by Django 4.2.1 on 2023-05-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_shoes_brand_alter_shoes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='photo',
            field=models.ImageField(null=True, upload_to='Image/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
