# Generated by Django 4.2.1 on 2023-05-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_alter_shoes_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='photo',
            field=models.ImageField(null=True, upload_to='Image', verbose_name='Фото'),
        ),
    ]
